services:
  app:
    build: .
    container_name: dpo_erp_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: dpo_erp_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: dpo_erp_mysql
    environment:
      MYSQL_DATABASE: dpo_erp
      MYSQL_USER: dpo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: dpo_erp_redis

  queue:
    build: .
    command: php artisan queue:work redis --tries=3
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - mysql
      - redis

  scheduler:
    build: .
    command: php artisan schedule:work
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - mysql
      - redis

volumes:
  mysql_data:
